version: "3.8"

services:
  # ===================== PostgreSQL ===================== #
  db:
    image: postgres:16-alpine
    container_name: sa_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: "123456"
      POSTGRES_DB: student_attendance
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d student_attendance"]
      interval: 10s
      timeout: 5s
      retries: 5

